"use client";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { motion } from "framer-motion";

const sections = [
  {
    title: "1. Acceptance of Terms",
    content: `By accessing or using the Dialix platform ("Service"), including the Dashboard, API, AI Voice Agents, Call Analytics, and related services, you agree to be bound by these Terms of Service. If you do not agree, you may not use the Service.

These terms apply to all users, including account administrators, team members, and API consumers.`,
  },
  {
    title: "2. Service Description",
    content: `Dialix provides an enterprise Voice AI platform that enables you to:

• **Create and manage AI Voice Agents** powered by ElevenLabs and large language models (GPT-4, GPT-4o Mini, etc.).
• **Provision and assign phone numbers** for inbound and outbound calling.
• **Analyze call performance** with transcriptions, quality scores, latency metrics, and evaluation criteria.
• **Integrate via Webhooks and API** to receive real-time call events and automate workflows.
• **Export data** in CSV and PDF formats for reporting and compliance.
• **Manage team access** through an admin panel with user and client management.`,
  },
  {
    title: "3. Account Registration",
    content: `To use the Service, you must create an account with a valid email address and password. You agree to:

• Provide accurate and complete registration information.
• Maintain the security of your account credentials.
• Promptly notify us of any unauthorized access.
• Accept responsibility for all activity under your account.

Accounts are issued per-client. Each client may have one or more AI agents and phone numbers.`,
  },
  {
    title: "4. Acceptable Use",
    content: `You agree not to use the Service to:

• Make calls that violate telecommunications regulations (TCPA, GDPR, etc.).
• Engage in harassment, fraud, or deceptive practices via AI agents.
• Transmit malicious content through agent prompts or system configurations.
• Attempt to reverse-engineer, decompile, or extract source code from the platform.
• Exceed rate limits or abuse the API in a manner that degrades service for others.
• Use the platform for any illegal purpose.

You are responsible for ensuring your AI agents comply with applicable laws, including consent requirements for call recording in your jurisdiction.`,
  },
  {
    title: "5. AI Agent Configuration",
    content: `When creating and configuring AI Voice Agents, you are responsible for:

• The content of system prompts, first messages, and knowledge base materials.
• Selecting appropriate language models, TTS models, and voice configurations.
• Setting reasonable maximum call durations and temperature parameters.
• Ensuring agent behavior complies with your industry regulations.

Dialix provides the infrastructure and AI capabilities; you retain responsibility for how agents are configured and what they communicate.`,
  },
  {
    title: "6. Data Ownership",
    content: `• **Your Data:** You retain ownership of all data you input into the platform, including agent configurations, prompts, knowledge bases, and call recordings.
• **Generated Data:** Transcriptions, analytics, quality scores, and evaluation results generated by the Service from your calls are considered your data.
• **Platform Data:** Aggregated, anonymized usage statistics may be used by Dialix to improve the Service.
• **Deletion:** You may delete your data at any time through the Dashboard. Deleted data is permanently removed within 30 days.`,
  },
  {
    title: "7. Service Availability",
    content: `We strive to maintain 99.99% uptime for the Dialix platform. However, we do not guarantee uninterrupted service and are not liable for:

• Scheduled maintenance windows (announced in advance).
• Third-party service disruptions (ElevenLabs, telephony carriers).
• Force majeure events.
• Issues caused by your network, configuration, or third-party integrations.`,
  },
  {
    title: "8. Fees and Payment",
    content: `• Service fees are based on your subscription plan and usage (minutes consumed, agents deployed, phone numbers provisioned).
• Fees are billed in advance on a monthly or annual basis.
• Failed payments may result in service suspension after a grace period.
• All fees are non-refundable except as required by applicable law.`,
  },
  {
    title: "9. Limitation of Liability",
    content: `To the maximum extent permitted by law, Dialix shall not be liable for:

• Indirect, incidental, special, or consequential damages.
• Lost profits, revenue, or business opportunities.
• Errors or inaccuracies in AI agent responses.
• Damages resulting from unauthorized access to your account.

Our total liability shall not exceed the fees paid by you in the twelve (12) months preceding the claim.`,
  },
  {
    title: "10. Termination",
    content: `• You may terminate your account at any time through the Dashboard settings.
• We may suspend or terminate your access for violation of these terms, with notice where practicable.
• Upon termination, your data will be retained for 30 days for export, then permanently deleted.
• Provisions regarding data ownership, limitation of liability, and indemnification survive termination.`,
  },
  {
    title: "11. Contact",
    content: `For questions about these Terms:

**Email:** legal@dialix.ai
**General Support:** support@dialix.ai

These terms were last updated on April 27, 2026.`,
  },
];

export default function TermsPageClient() {
  return (
    <>
      <Header />
      <main className="min-h-screen">
        {/* Hero */}
        <section className="relative overflow-hidden hero-gradient">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20 lg:py-28">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
              className="max-w-2xl mx-auto text-center"
            >
              <span className="eyebrow-badge mb-6 inline-flex">LEGAL</span>
              <h1 className="text-4xl md:text-5xl font-bold text-zinc-900 dark:text-white mb-4">
                Terms of Service
              </h1>
              <p className="text-lg text-zinc-600 dark:text-zinc-400">
                The terms governing your use of the Dialix Voice AI platform
                and related services.
              </p>
            </motion.div>
          </div>
          <div className="absolute inset-0 dot-grid opacity-40 pointer-events-none" />
        </section>

        {/* Content */}
        <section className="section-pad">
          <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="space-y-12">
              {sections.map((section, i) => (
                <motion.div
                  key={section.title}
                  initial={{ opacity: 0, y: 16 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.05, duration: 0.5 }}
                >
                  <h2 className="text-xl font-semibold text-zinc-900 dark:text-white mb-4">
                    {section.title}
                  </h2>
                  <div className="text-sm text-zinc-600 dark:text-zinc-400 leading-relaxed whitespace-pre-line">
                    {section.content.split(/(\*\*[^*]+\*\*)/).map((part, j) => {
                      if (part.startsWith("**") && part.endsWith("**")) {
                        return (
                          <strong key={j} className="text-zinc-800 dark:text-zinc-200">
                            {part.slice(2, -2)}
                          </strong>
                        );
                      }
                      return <span key={j}>{part}</span>;
                    })}
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
