"use client";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { motion } from "framer-motion";

const sections = [
  {
    title: "1. Information We Collect",
    content: `When you use Dialix, we collect the following types of information:

**Account Information:** Name, email address, company name, and password when you create an account.

**Call Data:** Call recordings, transcripts, duration, quality scores, and metadata generated by your AI voice agents through our integration with ElevenLabs.

**Usage Data:** Dashboard interactions, feature usage patterns, API calls, and webhook configurations.

**Payment Information:** Billing details processed through our secure payment provider. We do not store full credit card numbers.

**Technical Data:** IP addresses, browser type, device information, and access logs for security and performance monitoring.`,
  },
  {
    title: "2. How We Use Your Information",
    content: `We use collected information for the following purposes:

• **Service Delivery:** To operate your AI voice agents, process calls, generate analytics, and deliver the Dialix platform features including the Dashboard, Agent management, Phone Numbers, and Call Analytics.

• **Service Improvement:** To analyze usage patterns and improve platform performance, voice quality, and user experience.

• **Communication:** To send you service updates, security alerts, and support responses.

• **Security:** To protect against unauthorized access, detect fraud, and maintain platform integrity.

• **Compliance:** To meet legal obligations and respond to lawful requests from authorities.`,
  },
  {
    title: "3. Call Recording & Transcription",
    content: `Dialix processes call recordings and transcriptions through our integration with ElevenLabs' conversational AI. Key points:

• Call audio is streamed in real time and may be recorded for quality assurance and analytics purposes.
• Transcriptions are generated automatically and stored securely within your account.
• You maintain full ownership of your call data and can delete conversations at any time through the Analysis dashboard.
• Call recordings are stored with encryption at rest and in transit.
• You are responsible for obtaining necessary consent from call participants in accordance with applicable local laws.`,
  },
  {
    title: "4. Data Sharing",
    content: `We do not sell your personal data. We share information only in these circumstances:

• **Service Providers:** With ElevenLabs (AI voice processing), telephony providers (call routing), and infrastructure providers necessary to deliver the service.
• **Webhook Destinations:** When you configure webhooks in the Dashboard, call event data is sent to your specified endpoints.
• **Legal Requirements:** When required by law, court order, or governmental regulation.
• **Business Transfers:** In connection with a merger, acquisition, or sale of assets, with prior notice.`,
  },
  {
    title: "5. Data Security",
    content: `We implement enterprise-grade security measures to protect your data:

• End-to-end encryption for all data in transit (TLS 1.3) and at rest (AES-256).
• Role-based access control and JWT-based authentication for API and Dashboard access.
• Regular security audits and penetration testing.
• Infrastructure monitoring with 99.99% uptime SLA.
• Secure credential storage with bcrypt hashing for passwords.`,
  },
  {
    title: "6. Data Retention",
    content: `• Account data is retained for the duration of your active subscription.
• Call recordings and transcripts are retained according to your account settings and can be deleted at any time.
• Upon account deletion, all associated data is permanently removed within 30 days.
• Aggregated, anonymized analytics data may be retained indefinitely for service improvement.`,
  },
  {
    title: "7. Your Rights",
    content: `Depending on your jurisdiction, you may have the right to:

• **Access:** Request a copy of the personal data we hold about you.
• **Correction:** Request correction of inaccurate personal data.
• **Deletion:** Request deletion of your personal data and call recordings.
• **Export:** Export your data in a machine-readable format (CSV/PDF available from the Dashboard).
• **Objection:** Object to processing of your data for certain purposes.

To exercise these rights, contact us at privacy@dialix.ai.`,
  },
  {
    title: "8. Contact",
    content: `For privacy-related inquiries:

**Email:** privacy@dialix.ai
**General Support:** support@dialix.ai

This policy was last updated on April 27, 2026.`,
  },
];

export default function PrivacyPageClient() {
  return (
    <>
      <Header />
      <main className="min-h-screen">
        {/* Hero */}
        <section className="relative overflow-hidden hero-gradient">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20 lg:py-28">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
              className="max-w-2xl mx-auto text-center"
            >
              <span className="eyebrow-badge mb-6 inline-flex">LEGAL</span>
              <h1 className="text-4xl md:text-5xl font-bold text-zinc-900 dark:text-white mb-4">
                Privacy Policy
              </h1>
              <p className="text-lg text-zinc-600 dark:text-zinc-400">
                How we collect, use, and protect your data on the Dialix
                platform.
              </p>
            </motion.div>
          </div>
          <div className="absolute inset-0 dot-grid opacity-40 pointer-events-none" />
        </section>

        {/* Content */}
        <section className="section-pad">
          <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="space-y-12">
              {sections.map((section, i) => (
                <motion.div
                  key={section.title}
                  initial={{ opacity: 0, y: 16 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.05, duration: 0.5 }}
                >
                  <h2 className="text-xl font-semibold text-zinc-900 dark:text-white mb-4">
                    {section.title}
                  </h2>
                  <div className="text-sm text-zinc-600 dark:text-zinc-400 leading-relaxed whitespace-pre-line prose-strong:text-zinc-800 dark:prose-strong:text-zinc-200">
                    {section.content.split(/(\*\*[^*]+\*\*)/).map((part, j) => {
                      if (part.startsWith("**") && part.endsWith("**")) {
                        return (
                          <strong key={j} className="text-zinc-800 dark:text-zinc-200">
                            {part.slice(2, -2)}
                          </strong>
                        );
                      }
                      return <span key={j}>{part}</span>;
                    })}
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
